/* text initially generated by mkstub */

#include "stub.h"

value ML_XLoadQueryFont(v)
value *v;
{
	XFontStruct * r = XLoadQueryFont(
		(Display*) aarv(0),
		(const char*) sarv(1)
	);
	return Val_addr(r);
}

value ML_XFreeFont(v)
value *v;
{
	XFreeFont(
		(Display*) aarv(0),
		(XFontStruct*) aarv(1)
	);
	return unit;
}

value ML_XQueryFont(v)
value *v;
{
	XFontStruct * r = XQueryFont(
		(Display*) aarv(0),
		(XID) iarv(1)
	);
	return Val_addr(r);
}

#include <stdio.h>

value ML_XCreateFontSet(v)
value *v;
{
	XFontSet fontset;
        char **missing_charsets;
        int num_missing_charsets = 0;
        char *default_string;
        int i;
	XFontSet r = XCreateFontSet(
		(Display*) aarv(0),
		(const char*) sarv(1),
                &missing_charsets,
                &num_missing_charsets,
                &default_string
	);
        if (num_missing_charsets > 0) {
          (void)fprintf(stderr, "%s: the following charsets are missing:\n",
                        "librt");
          for (i = 0; i < num_missing_charsets; i++)
            (void)fprintf(stderr, "   %s\n", missing_charsets[i]);
          (void)fprintf(stderr, "The string %s\n", default_string);
          (void)fflush(stderr);
          XFreeStringList(missing_charsets);
        }
	return Val_addr(r);
}

value ML_XFreeFontSet(v)
value *v;
{
	XFreeFontSet(
		(Display*) aarv(0),
		(XFontSet) aarv(1)
	);
	return unit;
}
